### ISSUE TITLE
Trm0047a T m30

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-scores#21]
In Trm0047a T m30:

http://www.tassomusic.org/work/?id=Trm0047a&k=3eo

<img width="804" alt="screen shot 2017-04-18 at 7 37 39 pm" src="https://cloud.githubusercontent.com/assets/3487289/25161078/c351240a-246e-11e7-86aa-8a1da7b3305b.png">

There is a hyphen between `diè,` and `<E` which certainly should be removed.

-----------------------

If you want to try to fix it yourself, then go to line 229 on the page:

https://github.com/TassoInMusicProject/tasso-scores/blob/master/Trm/kern/Trm0047a-Non_egrave_questa_la_mano--Pallavicino_1579.krn#L229

And change the line from:

`1D	di&egrave;,	1F#X	di&egrave;,-	1A	di&egrave;,	1d	di&egrave;,`

to

`1D	di&egrave;,	1F#X	di&egrave;,	1A	di&egrave;,	1d	di&egrave;,`

(remove the dash)

And line 231 from:

`2AA	<E	2E	-<E	2A	<E	2c#X	<E`

to

`2AA	<E	2E	<E	2A	<E	2c#X	<E`

(remove the dash)

Remember to edit a file click on the pencil tool on the top right of the page:

<img width="329" alt="screen shot 2017-04-18 at 7 46 00 pm" src="https://cloud.githubusercontent.com/assets/3487289/25161263/bef85c92-246f-11e7-856c-344ded9a8ce8.png">

(after logging into Github).

Updates will not be immediately shown on the website (I still have to move the scores to the Stanford server).

**Comment by emilianoricciardi** [comment]
Done

**Comment by craigsapp** [comment]
That was fast :-)

I have moved the correction to the server, so if you close the TMP tab and open and new one, you should see the correction in the notation:

http://www.tassomusic.org/work/?id=Trm0047a&k=3eo

<img width="1028" alt="screen shot 2017-04-18 at 8 20 57 pm" src="https://cloud.githubusercontent.com/assets/3487289/25162045/8c91eb38-2474-11e7-81f1-f3a80103330e.png">

**Comment by emilianoricciardi** [comment]
OK. How do I go back to score viewing? I can only see parts now...

**Comment by craigsapp** [comment]
You click on the "T" button to turn of the tenor-only view.

**Comment by emilianoricciardi** [comment]
OK, I forgot about that...though probably users will have the same problem
(maybe we should add a "score" button?)

**Comment by craigsapp** [comment]
> though probably users will have the same problem

Only the musicologists :-)

One idea is that the icon could be "FS" for "Full Score", and would look like two joined circles.

I am using this font of icons, so if you see any single icon that would look good as a full-score icon, we could use that:

http://fontawesome.io/icons

---------------

Currently if you move your mouse over a highlighted part icon, there will be a tooltip like this appearing:

<img width="419" alt="screen shot 2017-04-18 at 8 39 25 pm" src="https://cloud.githubusercontent.com/assets/3487289/25162396/39e62f22-2477-11e7-93f2-ac53fd6e892a.png">

But that is not a very obvious feature.

Keyboard shortcut `0` (zero) will show all parts, and in this case pressing `3` for the Tenor part will toggle it off as well.

Some sort of help button for the page (discussed yesterday), might help in this sort of situation as well.
