### ISSUE TITLE
filename/contents inconsistencies

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-scores#33]
The file `Trm0284l-Questa_vostra_pietate--Costanzo_1616.krn ` should probably be renamed `Trm0284i-Questa_vostra_pietate--DiCostanzo_1616.krn `.  This was caused by the changing of catalog numbers for Trm0284.  Likewise for Trm0418, of which there were only two scores online, and these were easier to fix because of that. 

The file names/contents for the scores to Trm0284 and the other rime where the catalog numbers were adjusted should be checked.

**Comment by craigsapp** [comment]
Tr0284l file renamed Trm0284i:

http://www.tassomusic.org/work/?id=Trm0284i

**Comment by craigsapp** [comment]
Somewhat related, the file `Trm0060b-Lunge_da_voi_mio_core--Felis_1591.krn` has the year 1591, but the metadata for Trm0060b says that it should be 1590 ... but the RISM B/I number is 1591-18.

Also, Trm0060b is from a manuscript, so perhaps the RISM number and/or publication date are incorrect?

**Comment by craigsapp** [comment]
I changed the filename from `Trm0284i-Questa_vostra_pietate--Costanzo_1604.krn` to `Trm0284i-Questa_vostra_pietate--DiCostanzo_1604.krn` since the other two works by Di Costanzo add the "di":


```
Trm0284i-Questa_vostra_pietate--DiCostanzo_1604.krn
Trm0305k-Ne_i_vostri_dolci_baci--DiCostanzo_1604.krn
Trm0333l-Gelo_ha_Madonna_il_seno--DiCostanzo_1616.krn
```

**Comment by emilianoricciardi** [comment]
Trm0060b-Lunge_da_voi_mio_core--Felis_1591 is, in fact, Trm0060c and yes, it is from 1591. The editor who worked on this did not know that we had added another setting of Lunge da voi mio core.

**Comment by emilianoricciardi** [comment]
As for the real Trm0060b, by composer Fontanelli, the manuscript is dated 1590 and there is no RISM #
